#-------- NSO Features Automation --------

- EXEC:
  - devices:
    - device['device-name'] & device-group:
      - check-sync  # ----> Done !
      - sync-from  # ----> Done !
      - ssh/fetch-ssh-host-keys  # ----> Done !
      - live-status:
        - show - exec <command>  # ----> Done !
        - config - exec <command>  !!!!!# ----> *Pending*
  
- SHOW: 
  - aaa:
    - users  # ----> Done !
  - alarms:
    - alarm-list
    - summary
  - authgroups:
  - cli:
  - configuration:
    - commit:
      - changes
      - list
    - rollback:
      - changes  # ----> Done !
      - detailed configuration to rollback
  - devices:
    - device:
      - ['device-name']:  # ----> Done !
        - config:
          - any* ---->  # ----> Done !
        - platform:
          - model   # ----> Done !
          - version   # ----> Done !
          - serial number    # ----> Done !
          - alarms summary    # ----> Done !
        - service-list: !!!!!Cuando haya servicios definidos
        - services: !!!!!Cuando haya servicios definidos
    - authgroups:   # ----> Done !
    - device-group:   # ----> Done !
    - listing devices:   # ----> Done !
  - ncs-state:
    - version
  - packages:
    - packages:
      - package-version
      - oper-status
  - running-config:
    - device:
      - ['device-name']:  # ----> Done !
        - config:
          - any*  # ----> Done !
  - nacm:
    - users  # ----> Done !
    - user-groups  # ----> Done !
    - rule-lists  # ----> Done !
    - rule-actions  # ----> Done !
  - ha:
    - status
    - summary

- CONFIG:
  - aaa:
    - create users  # ----> Done !
  - devices:
    - authgroups  # ----> Done !
    - device-group: 
      - adding device to device-group   # ----> Done !
      - device-group single  # ----> Done !
      - device-group inside device-group  # ----> Done !
      - device-group complete estructure  # ----> Done !      
    - device['device-name'] create: # ----> Done !  
      - config:
        - any*
    - nacm:
      - users  # ----> Done !
      - user-groups  # ----> Done !
      - user-groups-asgined  # ----> Done !
      - rule-lists  # ----> Done !
      - rule-actions        # ----> Done !
  - commit:
    - dry-run  # ----> Done !     
    - no_networking  # ----> Done !
  - rollback:
    - perform a rollback
  - ha:
- kickers:

- PACKAGES & SERVICES:
  - NEXT-LEVEL UPCOMING

- FRAMEWORK:
  - DJANGO + SQL
  
- MONITORING:
  - TIG (TELEGRAF, INFLUXDB, GRAFANA)
  - ELK (ELASTICSEARCH, LOGSTASH, KIBANA)
